version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - email-collector-net

  api:
    image: elirant/collecto:latest
    container_name: collecto
    ports:
      - "80:80"
    volumes:
      - ./EmailCollector.Api/Data:/app/data
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:80
      - Redis__ConnectionString=redis:6379
      - EmailConfiguration:From=${EMAIL_FROM?Mandatory environment variable, check your .env file}
      - EmailConfiguration:SmtpServer=${EMAIL_SMTP_SERVER?Mandatory environment variable, check your .env file}
      - EmailConfiguration:Username=${EMAIL_USERNAME?Mandatory environment variable, check your .env file}
      - EmailConfiguration:Password=${EMAIL_PASSWORD?Mandatory environment variable, check your .env file}
      - ValidCorsOrigins=${VALID_CORS_ORIGINS}
      - COLLECTO_DOMAIN=${COLLECTO_DOMAIN}
    env_file:
      - .env
    networks:
      - email-collector-net

networks:
  email-collector-net:
    driver: bridge

volumes:
  data: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data