services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./redis-data:/data
    networks:
      - email-collector-net

  api:
    build:
      context: .
      dockerfile: EmailCollector.Api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./EmailCollector.Api/Data:/app/data
      - ./CustomEmailTemplates:/app/CustomEmailTemplates
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=redis:6379
      - EmailConfiguration:From=${EMAIL_FROM?Mandatory environment variable, check your .env file}
      - EmailConfiguration:SmtpServer=${EMAIL_SMTP_SERVER?Mandatory environment variable, check your .env file}
      - EmailConfiguration:Username=${EMAIL_USERNAME?Mandatory environment variable, check your .env file}
      - EmailConfiguration:Password=${EMAIL_PASSWORD?Mandatory environment variable, check your .env file}
      - ValidCorsOrigins=${VALID_CORS_ORIGINS}
      - COLLECTO_DOMAIN=${COLLECTO_DOMAIN}
      - DOTNET_LogLevel=Debug
    networks:
      - email-collector-net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    networks:
      - email-collector-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - email-collector-net

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - "8083:8978"
    environment:
      - CB_DB_SQLITE=true  # Enable SQLite support
    volumes:
      - ./EmailCollector.Api/Data:/app/data
      - ./dbeaver-data:/opt/cloudbeaver/workspace
    networks:
      - email-collector-net

networks:
  email-collector-net:
    driver: bridge

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data
  grafana:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana
