version: '3.8'

services:
  redis:
    image: collecto.azurecr.io/redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/redis-data:/data
    networks:
      - email-collector-net

  api:
    image: collecto.azurecr.io/collecto-api:latest
    container_name: email-collector-api
    ports:
      - "80:80"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/EmailCollector.Api/Data:/app/data
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:80
      - Redis__ConnectionString=redis:6379
      - EmailConfiguration:From=${EMAIL_FROM}
      - EmailConfiguration:SmtpServer=${EMAIL_SMTP_SERVER}
      - EmailConfiguration:Username=${EMAIL_USERNAME}
      - EmailConfiguration:Password=${EMAIL_PASSWORD}
    networks:
      - email-collector-net

networks:
  email-collector-net:
    driver: bridge

# volumes:
#   data: 
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: ./data